[package]
name = "valence-coprocessor-wasm-hello"
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[dependencies]
serde_json.workspace = true
valence-coprocessor-wasm.workspace = true

[lib]
crate-type = ["cdylib"]
