[package]
version = "0.1.0"
name = "state-proof-circuit"
edition = "2021"

[dependencies]
valence-coprocessor = { path = "../../../../core", default-features = false }
valence-coprocessor-domain = { path = "../../../", default-features = false, features = ["ethereum-circuit"] }
sp1-zkvm = "4.2.0"
