name: Update Cargo.nix
on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  crate2nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # We pass the "PAT" secret to the checkout action; if no PAT secret is available to the workflow runner (eg. Dependabot) we fall back to the default "GITHUB_TOKEN".
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v28
      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - name: Update Cargo.nix
        run: nix develop -c 'update-cargo-nix'
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name == 'push'
        with:
          commit_message: Update Cargo.nix
          file_pattern: Cargo.nix
          branch: ${{ github.head_ref }}
          commit_user_name: timewave-bot[bot]
          commit_user_email: parthiv@timewave.computer
          commit_options: '--signoff'
